### ISSUE TITLE
Jakarta namespace update

### ISSUE THREAD

**Issue by Maxouwell** [devlauer/plantuml-generator#126]
Hello,

Would you take a PR on a jakarta update for addJPAAnnotations and addJavaxAnnotations ?

I'm thinkinf of 
- For addJPAAnnotations, simply adding jakarta.* annotation search in JPAAnalyzerHelper  and allowing both on the doc
- For addJavaxAnnotations, doing one or more of :
  - Renaming the parameter to addJavaBeanAnnotations (breaking change, but I may be the only one using it)
  - Renaming the docs to addJavaBeanAnnotations
  - Adding jakarta.* annotation search in JavaxValidationAnalyzerHelper

What do you think ?
Regards

**Comment by devlauer** [comment]
An additional consideration of the jakarta namespace makes sense, because sooner or later all users switch to it. 
That you rename in this case the method addJavaxAnnotations as well as the associated internal methods and the class JavaxValidationAnalyzerHelper likewise. Regarding the breaking change I would like to see a hint in the documentation, so that other potential users know what to change to.
In this respect I would adopt the PR.

**Comment by devlauer** [comment]
Sorry for the delayed answer! Thanks you very much for your contribution! I've merged your PR and created a new version (2.4.0), which should be available in the next hours.

**Comment by Maxouwell** [comment]
Well it's was not that easy since I botched a part.
Fixed in #205

**Comment by Maxouwell** [comment]
And as I was on it, #206 for adding the jakarta Validation part

**Comment by devlauer** [comment]
@Maxouwell : Thank you very much for your contribution! And I am really sorry for the long wait! 
I released both pull requests as part of version 3.0.1. This version should be available within the next hours.
