### ISSUE TITLE
outputFilename missing or invalid in Intellij Maven

### ISSUE THREAD

**Issue by br0k1z0l1** [devlauer/plantuml-generator#25]
Hello!

When I try to run Maven build in Intellij, i get the following error:

`The parameters 'outputFilename' for goal de.elnarion.maven:plantuml-generator-maven-plugin:1.5.4:generate are missing or invalid`

I realized it doesn't matter what outputDirectory or outputFilename I set in pom.xml, it always stays the default, so the outputFilename stays empty (I guess).

Is my configuration wrong, or windows is messing something up? 

I attached a file with the maven run output. It's 245 lines, so figured you wouldn't want to scroll through it here on github.
[maven_build_output.txt](https://github.com/devlauer/plantuml-generator/files/9734742/maven_build_output.txt)

And this is my project's pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>codecool.com</groupId>
  <artifactId>geometry</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <name>geometry</name>
  <url>http://maven.apache.org</url>
<dependencies>
  <dependency>
    <groupId>de.elnarion.util</groupId>
    <artifactId>plantuml-generator-util</artifactId>
    <version>1.5.4</version>
  </dependency>
</dependencies>
  <build>
    <plugins>
      <plugin>
        <!-- Build an executable JAR -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
              <mainClass>com.codecool.geometry.Main</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>plantuml-generator-maven-plugin</artifactId>
        <groupId>de.elnarion.maven</groupId>
        <version>1.5.4</version>
        <executions>
          <execution>
            <id>generate-simple-diagram</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-test-sources</phase>
            <configuration>
              <outputDirectory>${basedir}</outputDirectory>
              <outputFilename>uml.txt</outputFilename>
              <scanPackages>
                <scanPackage>
                  com.codecool.geometry
                </scanPackage>
              </scanPackages>
              <whitelistRegexp>.*</whitelistRegexp>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
```

**Comment by devlauer** [comment]
Hi,

you are running the generate goal of the plantuml-generator-maven-plugin directly inside intellij. This is the same as you would run

`mvn plantuml-generator-maven-plugin:1.5.4:generate`

from the commandline. If you call a goal of a maven plugin directly, maven uses the configuration at plugin level or the configuration of the default execution id. Because there is no configuration in your pom.xml at plugin level and the plugin default execution id is default-cli and not generate-simple-diagram (the only configured execution id in your pom.xml), maven uses the default values of the plugin itself and this is why you get a maven error. 
To fix this error you can either change your execution id from generate-simple-diagram to default-cli, if you like to run the goal directly. Or you can run your custom execution id together with the plugin goal, which would be something like this on the commandline:

`mvn de.elnarion.maven:plantuml-generator-maven-plugin:1.5.4:generate@generate-simple-diagram`

(I'm not using IntelliJ, but here is a link to the IntelliJ documentation https://www.jetbrains.com/help/idea/work-with-maven-goals.html).
Or you can run maven with normal maven goals because the plugin goal generate is bound to the maven lifecycle phase generate-test-resources. Something like maven package / verify / install or deploy should work. In your case I would prefer

`mvn clean install`

I hope these hints help you with your struggle. If not feel free to reopen the issue again.

**Comment by br0k1z0l1** [comment]
Hey devlauer!

I changed the execution id to default-cli and it works.

Thanks for the hints!
