### ISSUE TITLE
Feature-Request: Add optional meta information for maven ascii-doc with plantuml plugin 

### ISSUE THREAD

**Issue by andrehertwig** [devlauer/plantuml-generator#3]
Hi
Great tool to generate class models out of code, but to get it into a generated documentation there are some manual steps required. It would be easier if this plugin could optionally generate the required macro-processor information for the ascii-doc plantUML plugin (https://asciidoctor.org/docs/asciidoctor-diagram/#diagram-block-macro). 

your plugin will generate the following (if using file output):
```
@startuml

class de.my.Class {
...
}
@enduml
```
If you want to include this into an ascii-doct(or) file with plantUML macro it will not be rendered :(
because the macro has no include directive..

so it would be nice to have some configurations to the get the follwing as output:
```
[plantuml, class-dia-my-component-model, svg] 
----
@startuml

class de.my.Class {
...
}
@enduml
----
```

with following configuration (for example):
```xml
<configuration>
    <enableAsciiDoctorMacoData>true</enableAsciiDoctorMacoData>
    <diagramFileName>class-dia-my-component-model</diagramFileName> <!-- default: 
        equals outputFilename without extension(?) -->
    <diagramImageFormat>svg</diagramImageFormat> <!-- default: svg or png -->
    <diagramLiteralBlock>----</diagramLiteralBlock> <!-- default: ---- -->
</configuration>
```

KR André

**Comment by devlauer** [comment]
Hi André,

thanks for your feature request and your commendation! 

The main purpose of this plugin was to create a plantuml class diagram so I did not generate any asciidoc metadata. But I will have a look on it in the next version. 

In the mean time you can include your generated plantuml file right in your asciidoc file in this way:

```
[plantuml, class-dia-my-component-model,svg]
----
include::path-to-generated-plantuml-file.pu[]
----
```

This works, because include statements are processed before block macros. I use it in several documents this way. But you are right, sometimes it is more comfortable to generate the whole asciidoc file with metadata for plantuml.

Kind regards
M.

**Comment by andrehertwig** [comment]
Hi

I tried the new feature, and it works very well :)

KR André
