### ISSUE TITLE
how to invoke?

### ISSUE THREAD

**Issue by ConnectedLife** [devlauer/plantuml-generator#5]
Please provide a working example of a command line for your examples.None of them work for me. Can this be executed?

**Comment by devlauer** [comment]
Hopefully i understand your question: you want to execute the examples directly on command line?
This is not possible. All examples on the README.md in the "Usage PlantUMLClassDiagramGenerator" section are Java Code Snippets. They are taken from the PlantUMLClassDiagramGeneratorTest class in the plantuml-generator-util module of this project, where all tests are green. If you want to execute the code on your command line, you either have to build your own java class with a main routine which you can be executed directly from command line or you have to use a maven pom.xml with the snippets from the "Usage maven plugin" section on the README.md and execute it via maven.

**Comment by ConnectedLife** [comment]
Thanks for your response. I can’t run it via maven, invoking it fails, trying to understand why. What cmd line & plugin version?

R,
D-

**Comment by devlauer** [comment]
To be able to help you, i need some more information about your problem:
* Which maven version do you use?
* Can you post your pom.xml or link it here?
* What happens if your maven build fails? 
* Which error message / stacktrace is shown?

Beside my questions there is a working maven example which part of the integration tests of the maven-plugin module. Perhaps https://github.com/devlauer/plantuml-generator/blob/master/plantuml-generator-maven-plugin/src/it/0001-simple-diagram-it/pom.xml helps you to get your project work. 

The current version of the maven plugin is 1.0.0

**Comment by devlauer** [comment]
There was no reply for nearly 6 months, so i will close this issue. If you still have a problem using this project please feel free to create a new issue, i will answer there...
