### ISSUE TITLE
Add JPA-Annotation to Class and Fields

### ISSUE THREAD

**Issue by christianAtmannheimer** [devlauer/plantuml-generator#8]
It would be a extraordinay option to add the JPA-Annotation contents like the name for Table and Column to the diagram.

Useful would be the tablename from the atTable - Annotation behind the ClassName in square brackets. i.E 'Classname [Tablename]'.
Also good would be to add the name from the atColumn -Annotation behind the fieldname. Maybe also in square brackets. i.E. 'fieldname [columnname]: type'

**Comment by devlauer** [comment]
I have added a new functionality for JPA-annotations as you requested, but I did not follow your design wishes, because I wanted a more UML-like style:
Annotations at class level should be shown as stereotypes. At field or relationship level there is no UML-like possibility (that I know), but they should be more general (perhaps I add some other annotation types later). So I used the same style as Java itself does. 

Because the @Table an the @Column annotation in JPA could be ommited, you need more information, if you want to know if a class or field is persisted and which column or table name it has. Therefore I've added some other JPA-annotations as well:
* Entity (only classes with this annotation are persisted)
* Transient (fields with this annotation are not persisted)
* Id (primary key column)
* OneToOne (better declaration of this relationship)
* OneToMany (better declaration of this relationship)
* ManyToOne (better declaration of this relationship)
* ManyToMany (better declaration of this relationship)

Just have a look on the following example and verify if it fits your needs:
![grafik](https://user-images.githubusercontent.com/3578132/93709636-18286280-fb40-11ea-9bc5-f4869a54f834.png)
If it does, I will create a new release and you can use this new option.

**Comment by devlauer** [comment]
As you told me via a private channel everything is fine, so I released the new version 1.2.0. 
It should be online on maven central in the next two hours.
